name: renatolotfi
favicon: null
layout_spectrum: 0.96388
typography_spectrum: 0.90761
title: Portfólio Renato Lotfi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#221e22'
    - '#f6f7f8'
    - '#6a7273'
    - '#f5b330'
    - '#00a4c9'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
