name: renatolotfi
favicon: null
layout_spectrum: 0.19393
typography_spectrum: 0.05181
title: Portfólio Renato Lotfi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#221e22'
    - '#f6f7f8'
    - '#6a7273'
    - '#f5b330'
    - '#00a4c9'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
